### ISSUE TITLE
Install fails on Windows 10: Fatal error in launcher: Unable to create process using '"c:\program files\python37\python.exe"...

### ISSUE THREAD

**Issue by maciej-blyng** [aws/aws-elastic-beanstalk-cli-setup#26] opened 2019-06-04 13:32 UTC
During the installation of EB-CLI3 
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html

I got the following error

> Fatal error in launcher: Unable to create process using '"c:\program files\python37\python.exe"  "D:\Blyng\aws-elastic-beanstalk-cli-setup\scripts\virtualenv\bin\virtualenv.exe" "C:\Users\maciej\.ebcli-virtual-env" -p "C:\Users\maciej\AppData\Local\Programs\Python\Python37\python.exe"'
> Exiting due to failure
> 

How can I get it installed?

**Comment by rahulrajaram** [comment] 2019-06-10 18:45
@maciej-blyng , are you sure this log output is accurate?

```
"D:\Blyng\aws-elastic-beanstalk-cli-setup\scripts\virtualenv\bin\virtualenv.exe" "C:\Users\maciej.ebcli-virtual-env" -p "C:\Users\maciej\AppData\Local\Programs\Python\Python37\python.exe"'
```

doesn't look like something the scripts might emit. Do yo really have the directory, `C:\Users\maciej.ebcli-virtual-env`?

**Comment by maciej-blyng** [comment] 2019-06-11 06:13
>are you sure this log output is accurate?

It's a raw output from the script. 

Can provide more logs, just tell me which ones.

**Comment by rahulrajaram** [comment] 2019-06-11 21:20
Can you try the following steps independently?

```ps1
.\scripts\install-python.ps1
python .\scripts\ebcli_installer.py
```

Let me know if this works.

**Comment by maciej-blyng** [comment] 2019-06-12 06:25
Running the installer that way completed the installation.
Thank you

**Comment by rahulrajaram** [comment] 2019-06-13 00:48
Glad it worked. I am unable to reproduce the original issue. I'll close this until I can find something actionable around it.

**Closed by rahulrajaram** 2019-06-13 00:48 UTC
